/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuario;

import usuario.*;
import conec.conection;
import static java.lang.System.out;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xavier
 */
public class buffet extends javax.swing.JFrame {
DefaultTableModel m;
Connection conexion;

    /**
     * Creates new form buffet
     */
    public buffet() {
            initComponents();
            //total=0;
            //sub_total =0.0;
        try {
            mostrar();
        } catch (SQLException ex) {
            Logger.getLogger(buffet.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
  void mostrar() throws SQLException{
       try {
            DefaultTableModel modelo=new DefaultTableModel();
            modelo.addColumn("cantidad");
            modelo.addColumn("nombre");
            modelo.addColumn("precio");
            
            buffet.setModel(modelo);
            String []datos=new String[3];
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery("select * from buffet");
          while(rs.next()){
              datos[0]=rs.getString(1);
              datos[1]=rs.getString(2);
              datos[2]=rs.getString(3);
              
              modelo.addRow(datos);
          }
         buffet.setModel(modelo);
        
        } catch (SQLException ex) {
            Logger.getLogger(buffet.class.getName()).log(Level.SEVERE, null, ex);
        }
      
  }
    void agregar(){
    int fila=buffet.getSelectedRow();
        if(fila>=0){
            
            
           
             out.println("cantidad:"+buffet.getValueAt(fila,0).toString()+"\nnombre:"+buffet.getValueAt(fila,1).toString()+"\nprecio"+buffet.getValueAt(fila,2).toString());
        }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mayor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        buffet = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel1.setText("BUFFET");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        agregar.setBackground(new java.awt.Color(0, 204, 0));
        agregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FONDS.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 70));

        mayor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(mayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 100, 30));

        buffet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(buffet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
       buffet.this.dispose();
       
    }//GEN-LAST:event_salirActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
       int fsel=buffet.getSelectedRow();
       String []registros= new String[3];
       String a,b,c;
       
        try{
         if(fsel==-1){
              JOptionPane.showMessageDialog(null,"DEBES SELECCIONAR UNA FILA");
                     }else{
               DefaultTableModel model= (DefaultTableModel)servicios.servicios.getModel();
    int filasele=buffet.getSelectedRow();
    registros[0]=buffet.getValueAt(filasele, 0).toString();
    registros[1]=buffet.getValueAt(filasele, 1).toString();
    registros[2]=buffet.getValueAt(filasele, 2).toString();
    model.addRow(registros);
   servicios.servicios.setModel(model); 
    //imprime el contenido de cada uno de los vectores
//   a=registros[0];
//   b=registros[1];
//   c=registros[2];
//   out.println("cantidad:"+a+"\nnombre:"+b+"\nprecio:"+c);
         }
       }catch(Exception w){
            
       }
        
//int fsel=buffet.getSelectedRow();
//try{
//String cantidad,nombre,precio;
////double calculo=0.0,x=0.0,igvs=0.0;
////int cati=0;
//        if(fsel==-1){
//              out.println("debe seleccionar una fila");
//       }else{
//m=(DefaultTableModel)buffet.getModel();
//cantidad=buffet.getValueAt(fsel,0).toString();
//nombre=buffet.getValueAt(fsel,1).toString();
//precio=buffet.getValueAt(fsel,2).toString();
//
////____________asta aqui se guardan los datos en variables_________________________
//m=(DefaultTableModel)servicios.servicios.getModel()
//String filaelemento[]={ cantidad,nombre,precio};
//m.addRow(filaelemento);



//------sumar datos-------
//calcula=(Double.parseDouble(precio)*Integer.parseInt(cantprod.getText()));
//total=total+calcula;
//igvs=total*0.19;***********debe ir dinamico;
//igv=igvs;
//sub_total=total-igvs;
//jTextfiel.setText(""+total);
//jTextfiel.setText(""+sub_total);
//jTextfiel.setText(""+igv);
//}
//}catch(Exception e){out.println("verificar la seleccion");}
//        
    }//GEN-LAST:event_agregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int fsel=buffet.getSelectedRow();
      
 
         DefaultTableModel m = (DefaultTableModel)buffet.getModel();
         String precio=(String) buffet.getValueAt(fsel, 0);
         String nombre=(String) buffet.getValueAt(fsel, 1);
         String total1=(String) buffet.getValueAt(fsel, 2);
         String can=mayor.getText();
         int x=(Integer.parseInt(total1) * Integer.parseInt(can));
        out.println(x);
         String total = String.valueOf(x);
           DefaultTableModel model= (DefaultTableModel)servicios.servicios.getModel();
          String filas []={can,nombre,total};
          model.addRow(filas);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buffet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buffet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buffet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buffet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buffet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTable buffet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mayor;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
conection cc=new conection();
Connection cn=cc.getConnection();
}
