/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuario;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import root.registro;
import conec.conection;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import static java.lang.System.out;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.Document;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import datos.datos;
import java.sql.PreparedStatement;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author xavier
 */
public class servicios extends javax.swing.JFrame {

   

    /**
     * Creates new form servicios
     */
public servicios() {
            initComponents();
        try {
            mostrar();
        } catch (SQLException ex) {
            Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
  void mostrar() throws SQLException{
      DefaultTableModel modelo=new DefaultTableModel();
      modelo.addColumn("cantidad");
      modelo.addColumn("nombre");
      modelo.addColumn("precio");
      servicios.setModel(modelo);
      String []datos=new String[3];
      //            Statement st=cn.createStatement();
//            ResultSet rs=st.executeQuery("select cantidad,nombre,precio from registro");
//          while(rs.next()){
//              datos[0]=rs.getString(1);
//              datos[1]=rs.getString(2);
//              datos[2]=rs.getString(3);
//              
//              modelo.addRow(datos);
//          }
servicios.setModel(modelo);
      
  }
  //se genera la suma del total
      public int sumarPreciosColumnas2(JTable tabla, int columna)  {

        int sumatoria1 = 0;

        for (int i = 0; i < tabla.getRowCount(); i++) {

            int sumatoria = Integer.parseInt(String.valueOf(tabla.getValueAt(i, columna)));
                
            sumatoria1 += sumatoria;
               datos.total+=sumatoria;
        }
    
        
     out.println("            "+"          "+sumatoria1);
      
       
       return sumatoria1;
       
}
   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buf = new javax.swing.JButton();
        carta = new javax.swing.JButton();
        refres = new javax.swing.JButton();
        extras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        servicios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        buf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buffet.png"))); // NOI18N
        buf.setText("BUFFET");
        buf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bufActionPerformed(evt);
            }
        });

        carta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        carta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carta.png"))); // NOI18N
        carta.setText("CARTA");
        carta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaActionPerformed(evt);
            }
        });

        refres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/soda.png"))); // NOI18N
        refres.setText("REFRESCOS");
        refres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresActionPerformed(evt);
            }
        });

        extras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        extras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ser.png"))); // NOI18N
        extras.setText("EXTRAS");
        extras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extrasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel2.setText("RESTAURANTE AZTECA");

        aceptar.setBackground(new java.awt.Color(153, 204, 255));
        aceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_payment_1954199.png"))); // NOI18N
        aceptar.setText("CUENTA");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        servicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(servicios);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(refres))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(extras, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(carta, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(aceptar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buf)
                    .addComponent(carta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refres)
                    .addComponent(extras, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bufActionPerformed
        // TODO add your handling code here:
        buffet a=new buffet();
        a.setVisible(true);
        
    }//GEN-LAST:event_bufActionPerformed

    private void cartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaActionPerformed
        // TODO add your handling code here:
        carta a=new carta();
        a.setVisible(true);
        
    }//GEN-LAST:event_cartaActionPerformed

    private void refresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresActionPerformed
        // TODO add your handling code here:
        refrescos a=new refrescos();
        a.setVisible(true);
        
        
    }//GEN-LAST:event_refresActionPerformed

    private void extrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extrasActionPerformed
        // TODO add your handling code here:
        extras a=new extras();
        a.setVisible(true);
        
    }//GEN-LAST:event_extrasActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
    try {
        // TODO add your handling code here:
        
        
        
        
        TableModel tableModel = servicios.getModel();
//int cols = servicios.getColumnCount();
////
//int fils = servicios.getRowCount();
//    int rows=0;
//    
////
//for(int i=0; i<fils; i++) {
////
//for(int j=0; j<cols; j++){
////
//System.out.println(servicios.getValueAt(i,j));
////
////System.out.println();
////
//}
//}
//int fsel = 0;
//         String cantidad,nombre,precio,a,b,c;
//         
//         DefaultTableModel m=( DefaultTableModel )servicios.getModel();
//         int cols = servicios.getColumnCount();
//         int fils = servicios.getRowCount();
//        
//        for(int i=0; i<cols;i++){
//             for(int j=0;j<fils;j++){
//                  out.println(servicios.getValueAt(i,j));
//              }
//        }
//         cantidad=servicios.getValueAt(fsel,0).toString();
//         nombre=servicios.getValueAt(fsel,1).toString();         precio=servicios.getValueAt(fsel,2).toString();
//        
//         a=cantidad;
//       b=nombre;
//         c=precio;
//        out.println(a+b+c);
int total = 0;
int subtota = 0;
int acumulador = total;
int nuevoNumero = 0;
//      
out.println("-------------------------------");
out.println("CANTIDAD    "+"NOMBRE  "+" TOTAL");
for (int i = 0; i < servicios.getRowCount(); i++) {
    subtota = Integer.parseInt(String.valueOf(servicios.getValueAt(i, 0)));
    String nombre=(String) servicios.getValueAt(i, 1);
    total = Integer.parseInt(String.valueOf(servicios.getValueAt(i, 2)));
    
    out.println("  "+subtota+"         "+nombre+"    "+total);
    
}





out.println("-------------------------------");
out.println("            "+"        "+" TOTAL");
out.println("            "+"          "+total);
sumarPreciosColumnas2(servicios, 2);




///-----------Datos de folio,mesa,personasl-----
 PreparedStatement pst3=cn.prepareStatement("INSERT INTO tiket(folio,mesa,num) VALUES(?,?,?)");
//       int  a=datos.folio;
//       int b=datos.mesa;
//       int c=datos.persona;

 pst3.setInt(1,datos.folio);
 pst3.setInt(2,datos.mesa);
 pst3.setInt(3,datos.persona);
  pst3.executeUpdate();
       out.println("exito");

//-------------------guardar datos-de la jtabla-----------------------------


 for(int i=0;i<servicios.getRowCount();i++){
       PreparedStatement pst=cn.prepareStatement("INSERT INTO venta(cantidad,nombre,precio) VALUES(?,?,?)");
            
             pst.setInt(1,Integer.parseInt((String) servicios.getValueAt(i, 0)));
              pst.setString(2,servicios.getValueAt(i, 1).toString());
                 pst.setInt(3,Integer.parseInt((String) servicios.getValueAt(i, 2)));
                 pst.executeUpdate();
         }
 
  //------------------total---------guardato
    
 PreparedStatement pst8=cn.prepareStatement("INSERT INTO total(total) VALUES(?)");
 pst8.setInt(1,datos.total);
 pst8.executeUpdate();
       out.println("exito del total"+datos.total);
//--------vaciar tabla-------------------------------
mostrar();

    } catch (SQLException ex) {
        Logger.getLogger(servicios.class.getName()).log(Level.SEVERE, null, ex);
    }
    
//    //_---------------------
                    String dir = "C:\\Users\\xavier\\Documents\\NetBeansProjects\\EL CHIDO\\restaurante\\src\\reportes\\report1.jrxml";
                   JasperReport reporteJasper = null;
       try {
           reporteJasper = JasperCompileManager.compileReport(dir);
      } catch (JRException ex) {
           Logger.getLogger(servicios.class.getName()).log(Level.SEVERE, null, ex);
       }
                   JasperPrint mostrarReporte = null;
       try {
          mostrarReporte = JasperFillManager.fillReport(reporteJasper, null, cc.getConnection());
        } catch (JRException ex) {
            Logger.getLogger(servicios.class.getName()).log(Level.SEVERE, null, ex);
        }
                  JasperViewer.viewReport(mostrarReporte);

     PreparedStatement pst2 = null;
      PreparedStatement pst6 = null;
      PreparedStatement pst8 = null;
    try {
        pst2 = cn.prepareStatement("truncate table venta");
         pst6 = cn.prepareStatement("truncate table tiket");
         pst8 = cn.prepareStatement("truncate table total");
    } catch (SQLException ex) {
        Logger.getLogger(servicios.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        pst2.executeUpdate();
        pst6.executeUpdate();
         pst8.executeUpdate();
    } catch (SQLException ex) {
        Logger.getLogger(servicios.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_aceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         inicio a=new inicio();
        a.setVisible(true);
        servicios.this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new servicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton buf;
    private javax.swing.JButton carta;
    private javax.swing.JButton extras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refres;
    public static javax.swing.JTable servicios;
    // End of variables declaration//GEN-END:variables
conection cc=new conection();
Connection cn=cc.getConnection();
}
