/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package root;

import conec.conection;
import static java.lang.System.out;
import usuario.inicio;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xavier
 */
public class registro extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
   public registro() {
            initComponents();
        try {
            mostrar();
        } catch (SQLException ex) {
            Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
  void mostrar() throws SQLException{
       try {
            DefaultTableModel modelo=new DefaultTableModel();
            modelo.addColumn("puesto");
            modelo.addColumn("nombre");
            modelo.addColumn("pin");
            
            jTable1.setModel(modelo);
            String []datos=new String[3];
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery("select * from usuario");
          while(rs.next()){
              datos[0]=rs.getString(1);
              datos[1]=rs.getString(2);
              datos[2]=rs.getString(3);
              
              modelo.addRow(datos);
          }
          jTable1.setModel(modelo);
        
        } catch (SQLException ex) {
            Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);
        }
      
  }
    void limpiar(){
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
}
   
 
 public static String leer(int max){
             Scanner sc=new Scanner(System.in);
          String cadena = "";
         do {
            System.out.println("Introduce la funcion a evaluar");
            cadena = sc.next();
            
            if(!(cadena.length() < max)){
                System.out.println("Error, la longitud no debe ser igual o mayo a:"+max+" caracteres");
            }
            
        } while (!(cadena.length() < max));

        return cadena;
        
         }   
   
void pin(int max,String a){

   
    if(!(a.length() < max)){
                 JOptionPane.showMessageDialog(null,"TU PIN DEBE DE SER DE 4 DIGITOS NO MAYOR:",":(",JOptionPane.ERROR_MESSAGE); 
            }
    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        ACTUALIZAR = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ingresar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        eliminar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        jPopupMenu1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPopupMenu1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenuItem2.setText("editar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ACTUALIZAR.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE USUARIOS");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRE:");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PIN:");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PUESTO:");

        ingresar.setBackground(new java.awt.Color(0, 204, 0));
        ingresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        ingresar.setText("INGRESAR");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        editar.setBackground(new java.awt.Color(255, 255, 255));
        editar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        eliminar.setBackground(new java.awt.Color(204, 0, 0));
        eliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(255, 255, 255));
        salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        UPDATE.setBackground(new java.awt.Color(255, 255, 255));
        UPDATE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ser.png"))); // NOI18N
        UPDATE.setText("ACTUALIZAR DATOS");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ACTUALIZARLayout = new javax.swing.GroupLayout(ACTUALIZAR);
        ACTUALIZAR.setLayout(ACTUALIZARLayout);
        ACTUALIZARLayout.setHorizontalGroup(
            ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ACTUALIZARLayout.createSequentialGroup()
                .addGroup(ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ACTUALIZARLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(ACTUALIZARLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(38, 38, 38)
                                .addGroup(ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ACTUALIZARLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ingresar)
                        .addGap(18, 18, 18)
                        .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eliminar)
                    .addComponent(UPDATE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ACTUALIZARLayout.setVerticalGroup(
            ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACTUALIZARLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(salir))
                .addGap(16, 16, 16)
                .addGroup(ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/adasdasdsaf.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ACTUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        general a=new general();
        a.setVisible(true);
        registro.this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
        String d=jTextField3.getText();
         String t=jTextField2.getText();
          String y=jTextField1.getText();
        String g="";
//        pin(5,d);
        int max=7;
        //-----------int max da el rango de que no debe ser mayor a ese numero
      if(d.equals(g)| t.equals(g) |y.equals(g)){
           JOptionPane.showMessageDialog(null,"DATOS IMCOMPLETOS",":(",JOptionPane.ERROR_MESSAGE);      
          
        }else  if(!(d.length() < max)){
                 JOptionPane.showMessageDialog(null,"TU PIN DEBE DE SER DE 8 DIGITOS NO MAYOR:",":(",JOptionPane.ERROR_MESSAGE);}
            else if(!(t.length() < max)){
                JOptionPane.showMessageDialog(null,"TU NOMBRE NO DEBE DE SER DE 8 DIGITOS NO MAYOR:",":(",JOptionPane.ERROR_MESSAGE);}
             else if(!(y.length() < max)){
                 JOptionPane.showMessageDialog(null,"TU PUESTO DEBE DE SER DE 8 DIGITOS NO MAYOR:",":(",JOptionPane.ERROR_MESSAGE);}
             
       
             else {
        
            
        try{
            PreparedStatement pst=cn.prepareStatement("INSERT INTO usuario(puesto,nombre,pin) VALUES(?,?,?)");
             pst.setString(1,jTextField1.getText());
      
//pst.setString(1,jTextField1.getText());
                     pst.setString(2,jTextField2.getText());
         pst.setInt(3,Integer.parseInt(jTextField3.getText()));
                    
            int executeUpdate = pst.executeUpdate();
                  if (cn==null){
                     JOptionPane.showMessageDialog(null,"elementos NNO insertados"); 
                  }
                  else{
                  JOptionPane.showMessageDialog(null,"elementos  insertados");
                  mostrar();
                  }
        }catch(SQLException e){
             JOptionPane.showMessageDialog(null,"ELEMENTOS YA EXISTENTES",":(",JOptionPane.ERROR_MESSAGE); 
        }catch(NumberFormatException e){JOptionPane.showMessageDialog(null,"DATO MAL INGRESADO\n"+"PIN:"+d+"\nNOBRE"+t+"\nPUESTO:"+y,":(",JOptionPane.ERROR_MESSAGE);}
        
        limpiar();
             }
    }//GEN-LAST:event_ingresarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
       int fila=jTable1.getSelectedRow();
        int cod;
        cod=Integer.parseInt(jTable1.getValueAt(fila,2).toString());
       
        try{
            if(fila>=0){
            PreparedStatement pst=cn.prepareStatement("DELETE FROM usuario WHERE pin='"+cod+"'");
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "elemento eliminado");
            mostrar();
            limpiar();
            out.println(cod);
            out.println(pst);
            }else{JOptionPane.showMessageDialog(null, "DEBES SELECCIONAR UN ELEMENTO");}
        }catch(Exception e){}

       
        
        
        
    }//GEN-LAST:event_eliminarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
       int fila=jTable1.getSelectedRow();
        if(fila>=0){
            // jTextField1.setEditable(false);
            // jTextField1.setEnabled(false); 
            jTextField1.setText(jTable1.getValueAt(fila,0).toString());
            jTextField2.setText(jTable1.getValueAt(fila,1).toString());
            jTextField3.setText(jTable1.getValueAt(fila,2).toString());
        }else{JOptionPane.showMessageDialog(null, "DEBES SELECCIONAR UN ELEMENTO");}
    }//GEN-LAST:event_editarActionPerformed

    private void jPopupMenu1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPopupMenu1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPopupMenu1AncestorAdded

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         int fila=jTable1.getSelectedRow();
        if(fila>=0){
            // jTextField1.setEditable(false);
            // jTextField1.setEnabled(false); 
            jTextField1.setText(jTable1.getValueAt(fila,0).toString());
            jTextField2.setText(jTable1.getValueAt(fila,1).toString());
            jTextField3.setText(jTable1.getValueAt(fila,2).toString());
            
            
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        // TODO add your handling code here:
        try{
           PreparedStatement pst=cn.prepareStatement
        ("UPDATE usuario SET puesto='"+jTextField1.getText()+"',nombre='"
                +jTextField2.getText()+"',pin='"+Integer.parseInt(jTextField3.getText())+"'WHERE nombre='"+jTextField2.getText()+"'");
       pst.executeUpdate();
       
       mostrar();
       }catch(Exception e){
           System.out.println(e.getMessage());
       }
       limpiar(); 
    }//GEN-LAST:event_UPDATEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ACTUALIZAR;
    private javax.swing.JButton UPDATE;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

conection cc=new conection();
Connection cn=cc.getConnection();

}
