/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package root;

/**
 *
 * @author xavier
 */
public class servicios_generales extends javax.swing.JFrame {

    /**
     * Creates new form servicios_generales
     */
    public servicios_generales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BUFFET = new javax.swing.JButton();
        CARTA = new javax.swing.JButton();
        REFRESCOS = new javax.swing.JButton();
        JUGOS = new javax.swing.JButton();
        EXTRAS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SALIR = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BUFFET.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BUFFET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buffet.png"))); // NOI18N
        BUFFET.setText("BUFFET");
        BUFFET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUFFETActionPerformed(evt);
            }
        });
        jPanel1.add(BUFFET, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 150, 60));

        CARTA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CARTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carta.png"))); // NOI18N
        CARTA.setText("CARTA");
        CARTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARTAActionPerformed(evt);
            }
        });
        jPanel1.add(CARTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 150, 60));

        REFRESCOS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        REFRESCOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/soda.png"))); // NOI18N
        REFRESCOS.setText("REFRESCOS");
        REFRESCOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REFRESCOSActionPerformed(evt);
            }
        });
        jPanel1.add(REFRESCOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, 62));

        JUGOS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JUGOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jug.png"))); // NOI18N
        JUGOS.setText("JUGOS");
        JUGOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUGOSActionPerformed(evt);
            }
        });
        jPanel1.add(JUGOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 150, 62));

        EXTRAS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EXTRAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ser.png"))); // NOI18N
        EXTRAS.setText("EXTRAS");
        EXTRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXTRASActionPerformed(evt);
            }
        });
        jPanel1.add(EXTRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, 60));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE SERVICIOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        SALIR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        jPanel1.add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Diapositiva1.JPG"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 920, 470));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUFFETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUFFETActionPerformed
        // TODO add your handling code here:
        registrobuffet a=new registrobuffet();
        a.setVisible(true);
        servicios_generales.this.dispose();
        
    }//GEN-LAST:event_BUFFETActionPerformed

    private void CARTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARTAActionPerformed
        // TODO add your handling code here:
        registrocarta a=new registrocarta();
        a.setVisible(true);
        servicios_generales.this.dispose();
    }//GEN-LAST:event_CARTAActionPerformed

    private void REFRESCOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REFRESCOSActionPerformed
        // TODO add your handling code here:
        registrorefresco a=new registrorefresco();
        a.setVisible(true);
        servicios_generales.this.dispose();
    }//GEN-LAST:event_REFRESCOSActionPerformed

    private void JUGOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUGOSActionPerformed
        // TODO add your handling code here:
        registrojugos a=new registrojugos();
        a.setVisible(true);
        servicios_generales.this.dispose();
    }//GEN-LAST:event_JUGOSActionPerformed

    private void EXTRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXTRASActionPerformed
        // TODO add your handling code here:
        registroextra a=new registroextra();
        a.setVisible(true);
        servicios_generales.this.dispose();
    }//GEN-LAST:event_EXTRASActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        general a=new general();
        a.setVisible(true);
        servicios_generales.this.dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(servicios_generales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(servicios_generales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(servicios_generales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(servicios_generales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new servicios_generales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUFFET;
    private javax.swing.JButton CARTA;
    private javax.swing.JButton EXTRAS;
    private javax.swing.JButton JUGOS;
    private javax.swing.JButton REFRESCOS;
    private javax.swing.JButton SALIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
